### ISSUE TITLE
ReactorCraft Interaction Issues

### ISSUE THREAD

**Issue by ghost** [kingrunes/Somnia#29] opened 2015-12-04 13:18 UTC
It seems that when a player sleeps in SMP with Somnia active, [ReactorCraft](https://github.com/ReikaKalseki/ReactorCraft) neutrons begin to ignore shielding and reactors blow up.  I'm not sure if it's on your or @Reika's side, but I figured there may be a check that needs to be added to the time speedup.  Interestingly enough, this does not happen in SSP.

**Comment by callumerrington** [comment] 2015-12-04 22:50
I haven't got any experience with ReactorCraft but my first guess is that @ReikaKalseki is using the global server tick event rather than the per world event. Regardless I don't think there's anything I can do since the issue is with the mechanics of ReactorCraft. I'll take a look through some of ReactorCraft's code if I get some spare time.

**Comment by ghost** [comment] 2015-12-04 22:53
Fair enough.  Thanks!

**Comment by ReikaKalseki** [comment] 2015-12-05 07:13
I use neither for neutrons. Everything is controlled by the TileEntities and Entities.

**Comment by ghost** [comment] 2015-12-05 14:13
Apparently, the problem is when the server runs behind; Somnia's only likely role is simply exacerbating the problem due to the increased game speed during sleep.  I've moved the bug report over to your tracker, Reika, although, to be honest, I don't know what can be done if a server skips ticks to catch up with the load...

**Comment by callumerrington** [comment] 2015-12-19 14:10
If the server skips ticks that shouldn't really affect tiles or entities since they don't know they were due an update anyway. What made you think that server lag was the cause?

**Comment by ghost** [comment] 2015-12-19 14:33
Well, the reason I assumed as much was because the problem seemed to occur when the game skipped ticks (which showed in the log).  However, it turned out to be a chunkloading issue.. neutrons continue to collect in a non-chunkloaded chunk, and when that chunk loads again, the sudden overload of heat explodes everything.  Since sleep happens far away from the nuclear reactor (for obvious reasons), the chunk was far enough away to unload after some time.

**Comment by callumerrington** [comment] 2015-12-19 17:04
Ah, fair enough. I guess I'll close this now then.

**Closed as completed by callumerrington** 2015-12-19 17:04 UTC
